### ISSUE TITLE
implementation on VIm

### ISSUE THREAD

**Issue by Mutaz94** [UUPharmacometrics/vim-nonmem#1]
I know this could be a naive question; how can I implement this syntax highlighter in VIM on windows. Thank you!

**Comment by Mutaz94** [comment]
I did it by adding a file type in the ftdetect folder, including this syntax 
```
au BufRead,BufNewFile *.mod,*.ctl set filetype=nonmem
```

**Comment by rikardn** [comment]
I put in the README instructions on how to activate via setting in .vimrc
